language: node_js
node_js:
  - "5.11.0"
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 id_rsa # this key should have push access 
  - ssh-add id_rsa
  - git remote add deploy ssh://root@23.105.213.131:27620/root/proxy/dotstack.git
  - git push deploy -f
